INSERT INTO food (name, category, quantity, refrigerated) VALUES
    ('cookies', 'snacks', 1, false),
    ('rice', 'grains', 2, false),
    ('blueberries', 'fruit', 2, false),
    ('muffin mix', 'dry', 19, false),
    ('broccoli', 'vegetables', 4, true),
    ('cauliflower', 'vegetables', 3, true),
    ('spaghetti pasta', 'pasta', 6, false),
    ('red pepper', 'fruit', 9, true),
    ('milk', 'dairy', 1, true),
    ('fettuccine', 'pasta', 1, false),
    ('kiwi', 'fruit', 5, true),
    ('strawberries', 'fruit', 2, true),
    ('goat cheese', 'dairy', 1, true),
    ('elbow macaroni', 'pasta', 2, false),
    ('fruit snacks', 'snacks', 12, false),
    ('rolled oats', 'grains', 4, true),
    ('lime', 'fruit', 8, true),
    ('lemon', 'fruit', 8, true),
    ('pretzels', 'snacks', 3, false),
    ('salsa', 'snacks', 1, true),
    ('sunflower seeds', 'dairy', 2, false),
    ('cheddar block', 'dairy', 2, true),
    ('pickle', 'fruit', 3, true),
    ('chia seeds', 'grains', 3, false),
    ('pancake mix', 'dry', 2, false);